save :
  version: '1'
  path: 'save'

hparas:
  epoch_num: 20
  optimizer: 'adam'
  lr: 0.001
  early_stop: True
  early_num: 5

type: 'MLP'
model:
  fc_dim: [50]
  dropout: 0.5

eval: 'acc'

data:
  path: 'data/SST-2'
  batch_size: 16

use_pre_embedding: True
embedding:
  name: 'glove'
  embedding_path: 'data/glove/glove.6B.100d.txt'
  emb_dim: 100
  emb_delimiter: ' '